## Basic Theme Info
name: WVU Brand Patterns
description: This is the WVU Brand Patterns theme built for CleanSlate. Originally authored by Adam Glenn.

## Attributes, Data and Variables
custom_site_attributes:
  # For Google Search Console
  - apply_link_1
  - apply_link_1_url
  - apply_link_2
  - apply_link_2_url
  - apply_link_3
  - apply_link_3_url
  - apply_url
  - bgcolor_gallery
  - bgcolor_adverts
  - bgcolor_calendar_widget
  - bgcolor_diptych
  - bgcolor_diptych_2
  - bgcolor_diptych_3
  - bgcolor_featurettes
  - bgcolor_featurettes_2
  - bgcolor_gallery
  - bgcolor_gallery_index
  - bgcolor_lede_text
  - bgcolor_pentaptych
  - bgcolor_pentaptych_2
  - bgcolor_pentaptych_3
  - bgcolor_profiles
  - bgcolor_profiles_index
  - bgcolor_quadriptych
  - bgcolor_quadriptych_2
  - bgcolor_quadriptych_3
  - bgcolor_social_media
  - bgcolor_testimonials
  - bgcolor_testimonials_index
  - bgcolor_triptych
  - bgcolor_triptych_2
  - bgcolor_triptych_3
  - bgcolor_twitter_widget
  - bgcolor_video
  - calendar_url
  - default_content_01
  - default_content_02
  - default_content_03
  - disable_masthead_search
  - facebook_url
  - github_url
  - give_url
  - google_site_verification
  - has_alternate_logo
  - instagram_url
  - jquery_defer
  - linkedin_url
  - masthead_college_link_address
  - masthead_college_link_title
  - masthead_color
  - masthead_logo_url
  - masthead_title
  - nav_depth
  - org_name
  - org_url
  - rss_url
  - search_action
  - show_apply_links
  - show_instructions
  - slot_00_masthead
  - slot_00_nav
  - twitter_handle
  - twitter_url
  - twitter_widget_id
  - youtube_url

## Template Config
# Specify which templates show up by default when creating a page
default_templates:
  content: backpage
  blog: blog_index
  article: blog_article
  error: backpage

## Optimizations
css:
  # Turn CSS compression on/off.
  compress: true
js:
  # Turn JavaScript compression and mangling on/off
  compress: true
  mangle: true
